### ISSUE TITLE
How does touchstone achive the fixed bottom toolbar?

### ISSUE THREAD

**Issue by mbrookes** [touchstonejs/touchstonejs#84]
Not an issue with TouchstoneJS - quite the opposite in fact, rather being my inability to replicate how you've managed to get a fixed bottom toolbar to work in WebView. Any pointers as to what the fundament structure is would be amazing!

So far I've managed to get it working in Chrome, half working in Safari (while breaking Chrome), but utterly broken in WebView in any case, despite hours of googling and experimentation, before trying to unpick how you've achieved it in TouchstoneJS.

(And I promise will look at using Touchstone directly when it hits 1.0!)

Thanks!

Edit: PS. Sorry for abusing github issues to ask this - if there's a forum where you guys hang out I'm all ears!

**Comment by mbrookes** [comment]
Happy to say that after two days of wrangling with this, I've (nearly) cracked it, shortly after posting this question. Typical!!

The answer in my case was to use `height: 100vh` for the container div to force it to the height of the viewport. The only problem I have now is that the content scroll bar 'leaks', allowing the footer to be dragged up about 20 pixels. Really odd...

Here's my CSS:

```css
.my-wrapper {
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    flex-direction: column;
    height: 100vh;
}

.my-header {
    height: 64px;
    min-height: 64px; /* Seems to be needed for WebView in addition to (or instead of?) height */
}

.my-content {
    -webkit-flex-grow: 1; /* Stretch the content div to fill the space between header and footer.*/
    flex-grow: 1;
    overflow-y: scroll; /* Scroll any content that exceeds the height of the div. */
}

.my-footer {
    height: 48px;
    min-height: 48px; 
}
```

And HTML:

```html
<div className="my-wrapper">
  <div className="my-header">
    Header...
  </div>
  <div className="my-content">
    Long Content Here...
  </div>
  <div className="my-footer">
    Footer...
  </div>
</div>
```

Closing this issue (especially as it never was one with Touchstone!), but any additional tips / advice will be gladly received!!
